-- Insert future-oriented jobs with AI impact analysis
-- Added Romanian translations (job_title_ro, description_ro columns)
INSERT INTO jobs_future (job_title_en, job_title_es, job_title_ro, description_en, description_es, description_ro, riasec_code, ai_impact_level, automation_risk, future_demand, required_skills) VALUES
-- High-growth future jobs
('AI/ML Engineer', 'Ingeniero de IA/ML', 'Inginer AI/ML', 'Develop and implement artificial intelligence solutions', 'Desarrollar e implementar soluciones de inteligencia artificial', 'Dezvoltă și implementează soluții de inteligență artificială', 'IRC', 'High', 'Low', 'High Growth', ARRAY['Python', 'Machine Learning', 'Deep Learning', 'Data Analysis']),
('Cybersecurity Specialist', 'Especialista en Ciberseguridad', 'Specialist în Securitate Cibernetică', 'Protect digital systems from cyber threats', 'Proteger sistemas digitales de amenazas cibernéticas', 'Protejează sistemele digitale de amenințările cibernetice', 'IEC', 'Medium', 'Low', 'High Growth', ARRAY['Network Security', 'Ethical Hacking', 'Risk Assessment', 'Incident Response']),
('UX/UI Designer', 'Diseñador UX/UI', 'Designer UX/UI', 'Design user-centered digital experiences', 'Diseñar experiencias digitales centradas en el usuario', 'Proiectează experiențe digitale centrate pe utilizator', 'AIS', 'Medium', 'Medium', 'High Growth', ARRAY['Design Thinking', 'Prototyping', 'User Research', 'Figma']),
('Data Analyst', 'Analista de Datos', 'Analist de Date', 'Extract insights from large datasets', 'Extraer información de grandes conjuntos de datos', 'Extrage informații din seturi mari de date', 'ICE', 'High', 'Medium', 'High Growth', ARRAY['SQL', 'Python', 'Statistics', 'Data Visualization']),
('Digital Marketing Specialist', 'Especialista en Marketing Digital', 'Specialist în Marketing Digital', 'Develop online marketing strategies', 'Desarrollar estrategias de marketing en línea', 'Dezvoltă strategii de marketing online', 'EAS', 'Medium', 'Medium', 'Growing', ARRAY['SEO', 'Social Media', 'Analytics', 'Content Marketing']),

-- Jobs with medium automation risk
('Project Manager', 'Gerente de Proyectos', 'Manager de Proiect', 'Coordinate and manage project execution', 'Coordinar y gestionar la ejecución de proyectos', 'Coordonează și gestionează execuția proiectelor', 'ESC', 'Medium', 'Medium', 'Growing', ARRAY['Agile', 'Leadership', 'Communication', 'Risk Management']),
('Content Creator', 'Creador de Contenido', 'Creator de Conținut', 'Produce engaging digital content', 'Producir contenido digital atractivo', 'Produce conținut digital captivant', 'AES', 'High', 'Medium', 'Growing', ARRAY['Video Editing', 'Social Media', 'Storytelling', 'SEO']),
('Healthcare Data Analyst', 'Analista de Datos de Salud', 'Analist de Date Medicale', 'Analyze healthcare data for insights', 'Analizar datos de salud para obtener información', 'Analizează datele medicale pentru informații', 'ISC', 'Medium', 'Medium', 'High Growth', ARRAY['Healthcare Systems', 'Statistics', 'HIPAA Compliance', 'SQL']),

-- Jobs with high automation risk
('Customer Service Representative', 'Representante de Servicio al Cliente', 'Reprezentant Servicii Clienți', 'Assist customers with inquiries and issues', 'Ayudar a clientes con consultas y problemas', 'Asistă clienții cu întrebări și probleme', 'SEC', 'High', 'High', 'Declining', ARRAY['Communication', 'Problem Solving', 'CRM Software', 'Empathy']),
('Data Entry Clerk', 'Empleado de Entrada de Datos', 'Operator Introducere Date', 'Input and maintain database information', 'Ingresar y mantener información de bases de datos', 'Introduce și menține informațiile din baze de date', 'CSI', 'High', 'High', 'Declining', ARRAY['Typing', 'Attention to Detail', 'Database Software', 'Accuracy']),
('Bookkeeper', 'Tenedor de Libros', 'Contabil', 'Maintain financial records for businesses', 'Mantener registros financieros para empresas', 'Menține înregistrările financiare pentru afaceri', 'CIS', 'High', 'High', 'Declining', ARRAY['Accounting Software', 'Mathematics', 'Organization', 'Attention to Detail']),

-- Emerging roles
('Sustainability Consultant', 'Consultor de Sostenibilidad', 'Consultant în Sustenabilitate', 'Help organizations implement sustainable practices', 'Ayudar a organizaciones a implementar prácticas sostenibles', 'Ajută organizațiile să implementeze practici sustenabile', 'IES', 'Low', 'Low', 'High Growth', ARRAY['Environmental Science', 'Policy Analysis', 'Project Management', 'Communication']),
('Robotics Engineer', 'Ingeniero en Robótica', 'Inginer în Robotică', 'Design and develop robotic systems', 'Diseñar y desarrollar sistemas robóticos', 'Proiectează și dezvoltă sisteme robotice', 'RIE', 'Medium', 'Low', 'High Growth', ARRAY['Programming', 'Mechanical Engineering', 'Electronics', 'AI']),
('Virtual Reality Developer', 'Desarrollador de Realidad Virtual', 'Dezvoltator Realitate Virtuală', 'Create immersive VR experiences', 'Crear experiencias inmersivas de RV', 'Creează experiențe VR imersive', 'ARI', 'Medium', 'Medium', 'Growing', ARRAY['Unity', 'C#', '3D Modeling', 'User Experience']);
